import type {
  Activity,
  CalendarEvent,
  CallLog,
  Email,
  EmailTemplate,
  FollowUp,
  Vendor,
} from "@/db/schema";

const day = (offset: number, hour = 10, minute = 0) => {
  const date = new Date();
  date.setDate(date.getDate() + offset);
  date.setHours(hour, minute, 0, 0);
  return date;
};

export const mockVendors: Vendor[] = [
  {
    id: "vendor-1",
    name: "Northstar Home Goods",
    type: "brand",
    status: "negotiating",
    website: "https://northstarhome.example",
    email: "wholesale@northstarhome.example",
    phone: "+1 (512) 555-0138",
    address: "640 Congress Avenue",
    city: "Austin",
    state: "TX",
    country: "USA",
    contactName: "Emily Carter",
    contactEmail: "emily@northstarhome.example",
    contactPhone: "+1 (512) 555-0171",
    contactTitle: "Wholesale Director",
    notes: "Strong catalog fit for Home & Kitchen. Requested reseller certificate and marketplace plan.",
    amazonCategories: "[\"Home & Kitchen\",\"Storage\"]",
    estimatedRevenue: "180000.00",
    priority: "high",
    pipelineStage: 2,
    hasPricingSheet: true,
    hasApplication: false,
    applicationDate: null,
    approvalDate: null,
    lastContactDate: day(-1, 14),
    nextFollowUpDate: day(1, 9),
    createdAt: day(-42),
    updatedAt: day(-1, 14),
  },
  {
    id: "vendor-2",
    name: "Evergreen Wellness Co.",
    type: "manufacturer",
    status: "application_sent",
    website: "https://evergreenwellness.example",
    email: "sales@evergreenwellness.example",
    phone: "+1 (303) 555-0124",
    address: "2200 Blake Street",
    city: "Denver",
    state: "CO",
    country: "USA",
    contactName: "Marcus Lee",
    contactEmail: "marcus@evergreenwellness.example",
    contactPhone: "+1 (303) 555-0188",
    contactTitle: "National Accounts Manager",
    notes: "Application submitted. Waiting for compliance review and opening order requirements.",
    amazonCategories: "[\"Health & Household\"]",
    estimatedRevenue: "260000.00",
    priority: "urgent",
    pipelineStage: 3,
    hasPricingSheet: true,
    hasApplication: true,
    applicationDate: day(-3),
    approvalDate: null,
    lastContactDate: day(-3),
    nextFollowUpDate: day(2, 11),
    createdAt: day(-65),
    updatedAt: day(-3),
  },
  {
    id: "vendor-3",
    name: "Atlas Outdoor Supply",
    type: "distributor",
    status: "approved",
    website: "https://atlasoutdoor.example",
    email: "accounts@atlasoutdoor.example",
    phone: "+1 (801) 555-0190",
    address: "85 West Pierpont Avenue",
    city: "Salt Lake City",
    state: "UT",
    country: "USA",
    contactName: "Sofia Ramirez",
    contactEmail: "sofia@atlasoutdoor.example",
    contactPhone: "+1 (801) 555-0155",
    contactTitle: "Dealer Success Manager",
    notes: "Approved account. Net-30 after the first two prepaid orders. MAP policy on file.",
    amazonCategories: "[\"Sports & Outdoors\"]",
    estimatedRevenue: "420000.00",
    priority: "high",
    pipelineStage: 4,
    hasPricingSheet: true,
    hasApplication: true,
    applicationDate: day(-26),
    approvalDate: day(-8),
    lastContactDate: day(-2),
    nextFollowUpDate: day(5),
    createdAt: day(-91),
    updatedAt: day(-2),
  },
  {
    id: "vendor-4",
    name: "Luma Beauty Labs",
    type: "manufacturer",
    status: "contacted",
    website: "https://lumabeauty.example",
    email: "partners@lumabeauty.example",
    phone: "+1 (310) 555-0167",
    address: "9300 Wilshire Boulevard",
    city: "Beverly Hills",
    state: "CA",
    country: "USA",
    contactName: "Nina Patel",
    contactEmail: "nina@lumabeauty.example",
    contactPhone: "+1 (310) 555-0112",
    contactTitle: "B2B Partnerships",
    notes: "Initial email opened twice. Follow up with a concise channel-control plan.",
    amazonCategories: "[\"Beauty & Personal Care\"]",
    estimatedRevenue: "145000.00",
    priority: "medium",
    pipelineStage: 1,
    hasPricingSheet: false,
    hasApplication: false,
    applicationDate: null,
    approvalDate: null,
    lastContactDate: day(-4),
    nextFollowUpDate: day(0, 15),
    createdAt: day(-18),
    updatedAt: day(-4),
  },
  {
    id: "vendor-5",
    name: "BrightNest Kids",
    type: "brand",
    status: "prospect",
    website: "https://brightnestkids.example",
    email: "hello@brightnestkids.example",
    phone: "+1 (615) 555-0107",
    address: "401 Broadway",
    city: "Nashville",
    state: "TN",
    country: "USA",
    contactName: "Daniel Brooks",
    contactEmail: "daniel@brightnestkids.example",
    contactPhone: "+1 (615) 555-0143",
    contactTitle: "Founder",
    notes: "Fast-growing educational toy brand. Research existing Amazon seller count before outreach.",
    amazonCategories: "[\"Toys & Games\"]",
    estimatedRevenue: "95000.00",
    priority: "medium",
    pipelineStage: 0,
    hasPricingSheet: false,
    hasApplication: false,
    applicationDate: null,
    approvalDate: null,
    lastContactDate: null,
    nextFollowUpDate: day(3),
    createdAt: day(-5),
    updatedAt: day(-5),
  },
  {
    id: "vendor-6",
    name: "Cobalt Office Products",
    type: "distributor",
    status: "on_hold",
    website: "https://cobaltoffice.example",
    email: "dealer@cobaltoffice.example",
    phone: "+1 (312) 555-0186",
    address: "180 North LaSalle Street",
    city: "Chicago",
    state: "IL",
    country: "USA",
    contactName: "Olivia Chen",
    contactEmail: "olivia@cobaltoffice.example",
    contactPhone: "+1 (312) 555-0119",
    contactTitle: "Channel Manager",
    notes: "Paused until Q3 due to territory capacity. Keep warm with a monthly check-in.",
    amazonCategories: "[\"Office Products\"]",
    estimatedRevenue: "110000.00",
    priority: "low",
    pipelineStage: 6,
    hasPricingSheet: true,
    hasApplication: false,
    applicationDate: null,
    approvalDate: null,
    lastContactDate: day(-12),
    nextFollowUpDate: day(18),
    createdAt: day(-74),
    updatedAt: day(-12),
  },
  {
    id: "vendor-7",
    name: "Pawline Naturals",
    type: "brand",
    status: "approved",
    website: "https://pawlinenaturals.example",
    email: "wholesale@pawlinenaturals.example",
    phone: "+1 (503) 555-0132",
    address: "1120 NW Couch Street",
    city: "Portland",
    state: "OR",
    country: "USA",
    contactName: "Grace Kim",
    contactEmail: "grace@pawlinenaturals.example",
    contactPhone: "+1 (503) 555-0196",
    contactTitle: "Wholesale Manager",
    notes: "Approved with $2,500 MOQ. First purchase order is being prepared.",
    amazonCategories: "[\"Pet Supplies\"]",
    estimatedRevenue: "310000.00",
    priority: "high",
    pipelineStage: 4,
    hasPricingSheet: true,
    hasApplication: true,
    applicationDate: day(-19),
    approvalDate: day(-4),
    lastContactDate: day(-1),
    nextFollowUpDate: day(1, 13),
    createdAt: day(-52),
    updatedAt: day(-1),
  },
  {
    id: "vendor-8",
    name: "Harbor & Pine Foods",
    type: "manufacturer",
    status: "rejected",
    website: "https://harborpine.example",
    email: "wholesale@harborpine.example",
    phone: "+1 (207) 555-0147",
    address: "72 Commercial Street",
    city: "Portland",
    state: "ME",
    country: "USA",
    contactName: "Ethan Walsh",
    contactEmail: "ethan@harborpine.example",
    contactPhone: "+1 (207) 555-0164",
    contactTitle: "Sales Operations",
    notes: "Marketplace sellers are not accepted at this time. Revisit in six months.",
    amazonCategories: "[\"Grocery & Gourmet Food\"]",
    estimatedRevenue: "0.00",
    priority: "low",
    pipelineStage: 5,
    hasPricingSheet: false,
    hasApplication: true,
    applicationDate: day(-31),
    approvalDate: null,
    lastContactDate: day(-22),
    nextFollowUpDate: null,
    createdAt: day(-80),
    updatedAt: day(-22),
  },
];

export const mockActivities: Activity[] = [
  { id: "activity-1", vendorId: "vendor-7", type: "email_received", subject: "Opening order terms confirmed", content: "Grace confirmed the $2,500 MOQ and sent updated inventory.", metadata: null, createdAt: day(-1, 13, 40) },
  { id: "activity-2", vendorId: "vendor-1", type: "call_made", subject: "Wholesale discovery call", content: "Discussed channel control, expected volume, and reseller documentation.", metadata: "{\"duration\":1080}", createdAt: day(-1, 14) },
  { id: "activity-3", vendorId: "vendor-3", type: "pricing_sheet_received", subject: "Spring price list received", content: "New dealer price list and inventory feed received.", metadata: null, createdAt: day(-2, 10) },
  { id: "activity-4", vendorId: "vendor-2", type: "application_submitted", subject: "Dealer application submitted", content: "Submitted reseller certificate, EIN letter, and company references.", metadata: null, createdAt: day(-3, 9) },
  { id: "activity-5", vendorId: "vendor-4", type: "email_sent", subject: "Amazon channel partnership inquiry", content: "Initial outreach sent to Nina Patel.", metadata: null, createdAt: day(-4, 11) },
  { id: "activity-6", vendorId: "vendor-5", type: "note", subject: "Prospect qualified", content: "Catalog has 36 products with stable demand and limited seller saturation.", metadata: null, createdAt: day(-5, 16) },
  { id: "activity-7", vendorId: "vendor-7", type: "status_change", subject: "Account approved", content: "Status moved from application sent to approved.", metadata: null, createdAt: day(-4, 15) },
  { id: "activity-8", vendorId: "vendor-6", type: "follow_up_scheduled", subject: "Quarterly check-in scheduled", content: "Reconnect when new territories reopen.", metadata: null, createdAt: day(-12, 9) },
  { id: "activity-9", vendorId: "vendor-8", type: "email_received", subject: "Marketplace policy response", content: "Brand is not onboarding marketplace resellers.", metadata: null, createdAt: day(-22, 12) },
  { id: "activity-10", vendorId: "vendor-3", type: "meeting", subject: "Account onboarding meeting", content: "Reviewed ordering portal, payment terms, and MAP policy.", metadata: null, createdAt: day(-7, 10) },
];

export const mockFollowUps: FollowUp[] = [
  { id: "follow-1", vendorId: "vendor-4", title: "Send second outreach email", description: "Reference Luma's retail positioning and include channel-control summary.", dueDate: day(0, 15), status: "pending", priority: "high", reminderSent: false, calendarEventId: null, completedAt: null, createdAt: day(-4), updatedAt: day(-4) },
  { id: "follow-2", vendorId: "vendor-1", title: "Share marketplace business plan", description: "Send projected order volume and operational overview.", dueDate: day(1, 9), status: "pending", priority: "high", reminderSent: false, calendarEventId: "gcal-demo-1", completedAt: null, createdAt: day(-1), updatedAt: day(-1) },
  { id: "follow-3", vendorId: "vendor-7", title: "Submit first purchase order", description: "Finalize SKU quantities with purchasing team.", dueDate: day(1, 13), status: "pending", priority: "urgent", reminderSent: false, calendarEventId: "gcal-demo-2", completedAt: null, createdAt: day(-1), updatedAt: day(-1) },
  { id: "follow-4", vendorId: "vendor-2", title: "Check application review status", description: "Ask whether compliance needs additional documentation.", dueDate: day(2, 11), status: "pending", priority: "medium", reminderSent: false, calendarEventId: null, completedAt: null, createdAt: day(-3), updatedAt: day(-3) },
  { id: "follow-5", vendorId: "vendor-5", title: "Find wholesale decision maker", description: "Verify Daniel's preferred outreach channel.", dueDate: day(3, 10), status: "pending", priority: "medium", reminderSent: false, calendarEventId: null, completedAt: null, createdAt: day(-5), updatedAt: day(-5) },
  { id: "follow-6", vendorId: "vendor-3", title: "Review updated price list", description: "Run profitability and buy-box checks on priority SKUs.", dueDate: day(-1, 9), status: "pending", priority: "urgent", reminderSent: true, calendarEventId: null, completedAt: null, createdAt: day(-4), updatedAt: day(-1) },
  { id: "follow-7", vendorId: "vendor-3", title: "Complete account onboarding", description: "Dealer portal credentials received and tested.", dueDate: day(-6, 14), status: "completed", priority: "medium", reminderSent: true, calendarEventId: null, completedAt: day(-6, 15), createdAt: day(-10), updatedAt: day(-6, 15) },
  { id: "follow-8", vendorId: "vendor-6", title: "Quarterly territory check-in", description: "Ask if marketplace territory capacity has changed.", dueDate: day(18, 10), status: "pending", priority: "low", reminderSent: false, calendarEventId: null, completedAt: null, createdAt: day(-12), updatedAt: day(-12) },
];

export const mockTemplates: EmailTemplate[] = [
  { id: "template-1", name: "Initial brand outreach", subject: "Wholesale partnership inquiry — {{vendor_name}}", body: "Hi {{contact_name}},\n\nI'm reaching out on behalf of our ecommerce retail business. We admire {{vendor_name}} and would like to discuss opening an authorized wholesale account.\n\nWe focus on responsible brand representation, MAP compliance, and long-term purchasing relationships. Would you be open to a brief introduction this week?\n\nBest,\nAlex", category: "initial_outreach", isActive: true, usageCount: 34, createdAt: day(-70), updatedAt: day(-12) },
  { id: "template-2", name: "First follow-up", subject: "Following up — {{vendor_name}} wholesale account", body: "Hi {{contact_name}},\n\nI wanted to follow up on my note about becoming an authorized wholesale partner for {{vendor_name}}. I'm happy to share our reseller certificate, business plan, and company references.\n\nIs there a better person on your team for this conversation?\n\nBest,\nAlex", category: "follow_up", isActive: true, usageCount: 27, createdAt: day(-62), updatedAt: day(-8) },
  { id: "template-3", name: "Application status", subject: "Wholesale application status — {{vendor_name}}", body: "Hi {{contact_name}},\n\nI'm checking on the wholesale application we submitted for {{vendor_name}}. Please let me know if your team needs any additional documentation to complete the review.\n\nThank you,\nAlex", category: "application", isActive: true, usageCount: 12, createdAt: day(-44), updatedAt: day(-3) },
  { id: "template-4", name: "Pricing request", subject: "Current wholesale catalog and price list", body: "Hi {{contact_name}},\n\nCould you please share the current wholesale catalog, price list, MOQ, and payment terms for {{vendor_name}}? We are preparing our opening order analysis.\n\nThank you,\nAlex", category: "pricing", isActive: true, usageCount: 19, createdAt: day(-35), updatedAt: day(-4) },
  { id: "template-5", name: "Approval thank you", subject: "Thank you for approving our {{vendor_name}} account", body: "Hi {{contact_name}},\n\nThank you for approving our wholesale account. We appreciate the opportunity to represent {{vendor_name}} and are reviewing the catalog for our first order now.\n\nBest,\nAlex", category: "thank_you", isActive: true, usageCount: 8, createdAt: day(-28), updatedAt: day(-2) },
];

export const mockEmails: Email[] = [
  { id: "email-1", vendorId: "vendor-7", gmailMessageId: "demo-message-1", gmailThreadId: "demo-thread-1", direction: "received", fromEmail: "grace@pawlinenaturals.example", toEmail: "alex@northpeakcommerce.com", subject: "Re: Opening order and current inventory", body: "Your account is active. I've attached current inventory and opening order terms.", htmlBody: null, isRead: false, templateId: null, sentAt: day(-1, 13, 40), createdAt: day(-1, 13, 40) },
  { id: "email-2", vendorId: "vendor-1", gmailMessageId: "demo-message-2", gmailThreadId: "demo-thread-2", direction: "sent", fromEmail: "alex@northpeakcommerce.com", toEmail: "emily@northstarhome.example", subject: "Marketplace plan and projected order volume", body: "Thanks for the call. Attached is our marketplace plan and projected order volume.", htmlBody: null, isRead: true, templateId: null, sentAt: day(-1, 15), createdAt: day(-1, 15) },
  { id: "email-3", vendorId: "vendor-2", gmailMessageId: "demo-message-3", gmailThreadId: "demo-thread-3", direction: "sent", fromEmail: "alex@northpeakcommerce.com", toEmail: "marcus@evergreenwellness.example", subject: "Wholesale application documents", body: "Please find our completed application and supporting business documents attached.", htmlBody: null, isRead: true, templateId: "template-3", sentAt: day(-3, 9), createdAt: day(-3, 9) },
  { id: "email-4", vendorId: "vendor-4", gmailMessageId: "demo-message-4", gmailThreadId: "demo-thread-4", direction: "sent", fromEmail: "alex@northpeakcommerce.com", toEmail: "nina@lumabeauty.example", subject: "Wholesale partnership inquiry — Luma Beauty Labs", body: "We'd like to discuss opening an authorized wholesale account.", htmlBody: null, isRead: true, templateId: "template-1", sentAt: day(-4, 11), createdAt: day(-4, 11) },
  { id: "email-5", vendorId: "vendor-3", gmailMessageId: "demo-message-5", gmailThreadId: "demo-thread-5", direction: "received", fromEmail: "sofia@atlasoutdoor.example", toEmail: "alex@northpeakcommerce.com", subject: "Spring dealer price list", body: "Attached is our spring price list and current inventory feed.", htmlBody: null, isRead: true, templateId: null, sentAt: day(-2, 10), createdAt: day(-2, 10) },
  { id: "email-6", vendorId: "vendor-8", gmailMessageId: "demo-message-6", gmailThreadId: "demo-thread-6", direction: "received", fromEmail: "ethan@harborpine.example", toEmail: "alex@northpeakcommerce.com", subject: "Re: Wholesale account request", body: "We are not onboarding marketplace resellers at this time.", htmlBody: null, isRead: true, templateId: null, sentAt: day(-22, 12), createdAt: day(-22, 12) },
];

export const mockCalls: CallLog[] = [
  { id: "call-1", vendorId: "vendor-1", twilioCallSid: "demo-call-1", fromNumber: "+1 (737) 555-0100", toNumber: "+1 (512) 555-0171", direction: "outbound", status: "completed", duration: 1080, recordingUrl: null, notes: "Discovery call. Positive fit; send business plan and volume forecast.", createdAt: day(-1, 14) },
  { id: "call-2", vendorId: "vendor-3", twilioCallSid: "demo-call-2", fromNumber: "+1 (801) 555-0155", toNumber: "+1 (737) 555-0100", direction: "inbound", status: "completed", duration: 465, recordingUrl: null, notes: "Sofia explained portal ordering and freight terms.", createdAt: day(-7, 10) },
  { id: "call-3", vendorId: "vendor-4", twilioCallSid: "demo-call-3", fromNumber: "+1 (737) 555-0100", toNumber: "+1 (310) 555-0112", direction: "outbound", status: "voicemail", duration: 42, recordingUrl: null, notes: "Left a concise voicemail after the initial email.", createdAt: day(-3, 16) },
  { id: "call-4", vendorId: "vendor-2", twilioCallSid: "demo-call-4", fromNumber: "+1 (737) 555-0100", toNumber: "+1 (303) 555-0188", direction: "outbound", status: "completed", duration: 720, recordingUrl: null, notes: "Reviewed required application documents and timelines.", createdAt: day(-9, 11) },
  { id: "call-5", vendorId: "vendor-6", twilioCallSid: "demo-call-5", fromNumber: "+1 (312) 555-0119", toNumber: "+1 (737) 555-0100", direction: "inbound", status: "completed", duration: 300, recordingUrl: null, notes: "Territory is full until Q3; agreed to reconnect later.", createdAt: day(-12, 9) },
];

export const mockEvents: CalendarEvent[] = [
  { id: "event-1", vendorId: "vendor-1", googleEventId: "google-demo-1", title: "Northstar partnership review", description: "Review channel plan and answer account questions.", startTime: day(1, 9), endTime: day(1, 9, 30), location: "Google Meet", attendees: "[\"emily@northstarhome.example\"]", meetingLink: "https://meet.google.com/", reminderMinutes: 30, isSynced: true, createdAt: day(-2), updatedAt: day(-2) },
  { id: "event-2", vendorId: "vendor-7", googleEventId: "google-demo-2", title: "Opening order planning", description: "Confirm first PO quantities and in-stock substitutions.", startTime: day(2, 13), endTime: day(2, 14), location: "Zoom", attendees: "[\"grace@pawlinenaturals.example\"]", meetingLink: "https://zoom.us/", reminderMinutes: 30, isSynced: true, createdAt: day(-1), updatedAt: day(-1) },
  { id: "event-3", vendorId: "vendor-2", googleEventId: "google-demo-3", title: "Application review check-in", description: "Resolve outstanding compliance questions.", startTime: day(4, 11), endTime: day(4, 11, 30), location: "Phone", attendees: "[\"marcus@evergreenwellness.example\"]", meetingLink: null, reminderMinutes: 60, isSynced: true, createdAt: day(-3), updatedAt: day(-3) },
  { id: "event-4", vendorId: "vendor-3", googleEventId: "google-demo-4", title: "Atlas catalog review", description: "Review profitable SKU shortlist with purchasing.", startTime: day(7, 10), endTime: day(7, 11), location: "Conference room", attendees: "[]", meetingLink: null, reminderMinutes: 30, isSynced: false, createdAt: day(-1), updatedAt: day(-1) },
];

export const mockIntegrations = [
  { provider: "gmail", isEnabled: true },
  { provider: "google_calendar", isEnabled: true },
  { provider: "twilio", isEnabled: false },
];

export const productProfile = {
  title: "BrandPilot",
  subtitle: "Amazon Wholesale Account Acquisition CRM",
  promise: "Turn scattered brand outreach into a repeatable, measurable wholesale growth system.",
  company: "NorthPeak Commerce",
  idealCustomers: [
    "Amazon wholesale sellers building direct brand and distributor accounts",
    "Small ecommerce teams managing 100–5,000 vendor relationships",
    "Wholesale agencies running outreach for multiple seller portfolios",
    "Operations managers replacing spreadsheets, inbox labels, and manual reminders",
  ],
  qualities: [
    "Purpose-built for Amazon wholesale workflows",
    "Fast, clear, and easy for small teams to adopt",
    "One vendor record for every email, call, task, document, and decision",
    "Measurable pipeline with conversion and activity KPIs",
    "Integration-ready architecture for Gmail, Calendar, and Twilio",
    "Responsive, accessible interface with role-ready navigation",
  ],
  techStack: [
    { layer: "Frontend", value: "Next.js 16, React 19, TypeScript" },
    { layer: "Design", value: "Tailwind CSS 4, Lucide icons, responsive UI" },
    { layer: "Demo data", value: "Typed in-memory fixtures — no database required" },
    { layer: "Production data", value: "Firebase Firestore + Firebase Authentication" },
    { layer: "Email", value: "Gmail API with Google OAuth 2.0" },
    { layer: "Calendar", value: "Google Calendar API and event webhooks" },
    { layer: "Calling", value: "Twilio Voice, status callbacks, recordings" },
    { layer: "Hosting", value: "Netlify or Vercel with GitHub CI/CD" },
    { layer: "Quality", value: "Zod validation, TypeScript checks, automated QA" },
  ],
};
